import { contentGenerationRules, mentorSystemPrompt } from "./prompts";
import type { AgentDefinition } from "./types";

const strictJson = "Return structured JSON only. Preserve Hebrew RTL text and LaTeX math exactly.";

export const agentDefinitions: AgentDefinition[] = [
  {
    id: "master-project-manager",
    name: "Master Project Manager",
    role: "Coordinates the complete Calculus 2 exam-prep build for a 90+ Moed A target.",
    systemPrompt: `${strictJson} Detect missing materials, inconsistent numbering, unclear topic coverage, and whether the pipeline is ready to publish.`,
    inputDescription: "Course config, source inventory, agent outputs, validation results.",
    outputSchemaDescription: "{ overview, missingFilesReport, processingStatus, recommendedNextActions, globalExamPrepStrategy, warnings }",
    validationRules: ["Must preserve the 13-week / 9-available-week distinction.", "Must flag recitation offset assumptions."],
    whenToRun: "Before a pipeline run, after major stages, and before publishing generated data.",
  },
  {
    id: "lecture-analysis",
    name: "Lecture Analysis",
    role: "Extracts definitions, theorems, formulas, proofs, examples, remarks and conclusions from lecture files.",
    systemPrompt: `${strictJson} ${contentGenerationRules}`,
    inputDescription: "One lecture source file plus extracted text and lecture/week number.",
    outputSchemaDescription: "{ lecture, topics, definitions, theorems, formulas, proofPatterns, examples, mustKnowList, sourceReferences }",
    validationRules: ["Every theorem needs assumptions and conclusion.", "Every item needs source references when page data exists."],
    whenToRun: "After text extraction for lecture files.",
  },
  {
    id: "recitation-analysis",
    name: "Recitation Analysis",
    role: "Determines what a recitation actually practices and links it to the practiced lecture.",
    systemPrompt: `${strictJson} Detect if Recitation N practices Lecture N-1, older material, mixed material, or something else.`,
    inputDescription: "Recitation file, extracted text, recitation number, expected practiced lecture number.",
    outputSchemaDescription: "{ recitation, practicedLectureNumber, practicedTopics, solvedQuestions, proofPatterns, commonMistakes, examRelevance }",
    validationRules: ["Must explicitly confirm or reject the N -> N-1 mapping.", "Every solved question needs a topic classification or warning."],
    whenToRun: "After text extraction for recitation/tutorial files.",
  },
  {
    id: "homework-analysis",
    name: "Homework Analysis",
    role: "Maps homework questions to topics, techniques, theorem dependencies and exam similarity.",
    systemPrompt: `${strictJson} Identify required tools, difficulty, recurring patterns and must-review-before-exam questions.`,
    inputDescription: "Homework source file, extracted text, week/homework number, known topic map.",
    outputSchemaDescription: "{ homework, questionBank, difficultyClassification, examSimilarityScores, requiredReviewList }",
    validationRules: ["Exam similarity requires evidence.", "Question records must keep source references."],
    whenToRun: "After text extraction for homework files.",
  },
  {
    id: "summary-integration",
    name: "Summary Integration",
    role: "Compares summaries to lectures and turns them into clean study pages.",
    systemPrompt: `${strictJson} ${contentGenerationRules}`,
    inputDescription: "Summary file, extracted text, related lectures, current theory items.",
    outputSchemaDescription: "{ summarySections, enhancedExplanations, topicStudyPages, conflicts }",
    validationRules: ["Conflicts must cite both sources.", "Simplified explanations cannot drop formal conditions."],
    whenToRun: "After lecture analysis or when a summary is added.",
  },
  {
    id: "past-exam-analysis",
    name: "Past Exam Analysis",
    role: "Analyzes past exams to identify high-value topics, proofs, formulas and question structures.",
    systemPrompt: `${strictJson} Build frequency maps and answer what must be mastered for 90+ on Moed A.`,
    inputDescription: "Past exam files, extracted text, homework and recitation question banks.",
    outputSchemaDescription: "{ examQuestions, topicFrequency, theoremFrequency, formulaFrequency, proofPatternFrequency, homeworkSimilarity, strategy, practiceOrder }",
    validationRules: ["Frequency maps must include denominator.", "Similarity requires linked question ids or low-confidence warning."],
    whenToRun: "After past exam extraction and after homework/recitation questions exist.",
  },
  {
    id: "topic-organizer",
    name: "Topic Organizer",
    role: "Creates a topic-first learning map from all source analyses.",
    systemPrompt: `${strictJson} Do not hardcode final topics; derive and merge topics from actual materials.`,
    inputDescription: "Lecture, recitation, homework, summary and exam analyses.",
    outputSchemaDescription: "{ topics, topicPages, topicToWeekMap, topicToExamMap, masteryRequirements }",
    validationRules: ["High-frequency exam topics need practice paths.", "Duplicate topics should be merged with aliases."],
    whenToRun: "After source-specific analyses.",
  },
  {
    id: "week-organizer",
    name: "Week Organizer",
    role: "Builds the 13-week map and makes the lecture-recitation-homework offset visible.",
    systemPrompt: `${strictJson} Never group Lecture N and Recitation N as identical content without evidence.`,
    inputDescription: "Classified files and source-specific analysis outputs.",
    outputSchemaDescription: "{ weeks, alignmentReport, missingMaterialsReport, weekPages }",
    validationRules: ["Weeks 10-13 remain visible as missing when no source exists.", "Recitation offset must be represented."],
    whenToRun: "After file classification and after source analyses.",
  },
  {
    id: "ui-ux-design",
    name: "UI/UX Design",
    role: "Defines serious Hebrew-first academic UI for long study sessions.",
    systemPrompt: `${strictJson} Keep UI clean, RTL, math-friendly, premium and non-childish.`,
    inputDescription: "Course map, topic map, progress model and route list.",
    outputSchemaDescription: "{ pageLayouts, componentMap, designRules, emptyStates }",
    validationRules: ["No fake processed data.", "Every empty state must explain the next processing step."],
    whenToRun: "Before route data generation and UI iteration.",
  },
  {
    id: "exam-plan",
    name: "Exam Plan",
    role: "Builds the personalized Moed A study plan for a 90+ target.",
    systemPrompt: `${strictJson} Prioritize by exam frequency, weakness, homework similarity and proof/formula memorization.`,
    inputDescription: "Topic map, frequency maps, progress items, available study days.",
    outputSchemaDescription: "{ readinessScore, priorityOrder, dailyTasks, mustReviewList, practiceOrder }",
    validationRules: ["Plan must adapt to weak areas.", "Past exams and homework must both appear in the plan."],
    whenToRun: "After exam analysis and whenever progress changes.",
  },
  {
    id: "progress-mastery",
    name: "Progress & Mastery",
    role: "Turns progress events into mastery, weak-area and next-review recommendations.",
    systemPrompt: `${strictJson} Track statuses: not_started, seen, understood, needs_review, weak, mastered.`,
    inputDescription: "Progress items, topic map, theorem bank, formula bank, proof pattern bank and question bank.",
    outputSchemaDescription: "{ masteryPercentages, weakTopics, nextReviewRecommendations, readinessScore }",
    validationRules: ["Readiness must be explainable.", "Recommendations point to concrete item ids."],
    whenToRun: "On dashboard load and progress updates.",
  },
  {
    id: "mentor-prompt",
    name: "Mentor Prompt",
    role: "Produces mentor behavior, retrieval and source-priority rules.",
    systemPrompt: mentorSystemPrompt,
    inputDescription: "Course map, topic map, exam strategy and source priority rules.",
    outputSchemaDescription: "{ systemPrompt, responseRules, retrievalRules, sourcePriorityRules, examPrepRules }",
    validationRules: ["Hebrew by default.", "Hints before full solutions in practice mode."],
    whenToRun: "After topic and exam maps exist.",
  },
  {
    id: "markdown-html-content",
    name: "Markdown/HTML Content",
    role: "Converts analyzed material into clean Markdown/HTML-ready study sections.",
    systemPrompt: `${strictJson} Preserve RTL, LTR math/English and valid LaTeX. Use callouts for definitions, theorems, formulas, exam tips and common mistakes.`,
    inputDescription: "Analyzed lectures, summaries, topics, formulas, theorems and proof patterns.",
    outputSchemaDescription: "{ markdownSections, htmlReadySections, calloutMetadata, linkedItems }",
    validationRules: ["No broken LaTeX delimiters.", "Callouts need source references when available."],
    whenToRun: "After topic organization and summary integration.",
  },
];
